name: Get Top Followers
# Controls when the action will run. Triggers the workflow on push events
on:
  push:
    branches: [ main ]
  schedule:
  - cron: "* * * * *"
  
  workflow_dispatch:
  
jobs:
  top-followers:
    runs-on: ubuntu-latest
    
